### ISSUE TITLE
Geek-Stuff

### ISSUE THREAD

**Issue by chelobotix** [chelobotix/Geek-Stuff#19]
Project Kanban link: [https://github.com/chelobotix/Geek-Stuff/projects/1](https://github.com/chelobotix/Geek-Stuff/projects/1)
3 participants:
Team member 1: Felipe Haybar [https://github.com/Feliverse](https://github.com/Feliverse)
Team member 2: Anderson Canales [https://github.com/anderCM](https://github.com/anderCM)
Team member 3: Marcelo Alarcon [https://github.com/chelobotix](https://github.com/chelobotix)

**Comment by AmaduKamara** [comment]
# Status: Approved 🟢 🟢 🟢

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ Set up the Kanban board correctly 👍🏽
✅ Tasks are shared fairly 👍🏽
✅ Tasks are assigned to team members correctly 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
